"""create actions table

Revision ID: 1713516d6639
Revises: c78de5511ff6
Create Date: 2025-05-08 17:54:38.073224

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1713516d6639'
down_revision = 'c78de5511ff6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_action_schemas', schema=None) as batch_op:
        batch_op.drop_index('model_id')

    op.drop_table('device_action_schemas')
    with op.batch_alter_table('device_models', schema=None) as batch_op:
        batch_op.drop_index('schema_id')
        batch_op.drop_constraint('device_models_ibfk_2', type_='foreignkey')
        batch_op.drop_column('schema_id')

    with op.batch_alter_table('device_schemas', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_model_kind', ['model_id', 'kind'])
        batch_op.create_foreign_key(None, 'device_models', ['model_id'], ['id'])

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.alter_column('topic_prefix',
               existing_type=mysql.VARCHAR(length=200),
               comment="Root topic, e.g. 'shellies'",
               existing_comment="Root topic, e.g. 'shelly/1ABC23'",
               existing_nullable=False)
        batch_op.drop_index('serial_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index('serial_number', ['serial_number'], unique=True)
        batch_op.alter_column('topic_prefix',
               existing_type=mysql.VARCHAR(length=200),
               comment="Root topic, e.g. 'shelly/1ABC23'",
               existing_comment="Root topic, e.g. 'shellies'",
               existing_nullable=False)

    with op.batch_alter_table('device_schemas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_model_kind', type_='unique')

    with op.batch_alter_table('device_models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schema_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('device_models_ibfk_2', 'device_schemas', ['schema_id'], ['id'])
        batch_op.create_index('schema_id', ['schema_id'], unique=True)

    op.create_table('device_action_schemas',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('model_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('schema', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=False),
    sa.Column('version', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['device_models.id'], name='device_action_schemas_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('device_action_schemas', schema=None) as batch_op:
        batch_op.create_index('model_id', ['model_id'], unique=True)

    # ### end Alembic commands ###
